### ISSUE TITLE
Log metrics for generic exhibit 21/10k basic info extraction

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/mozilla-sec-eia#33]
### Overview

#34 outlines computing/logging metrics for exhibit 21 extraction on the labelled validation set. We also want to track performance on running table extraction on generic filings which we don't have labels for. This will be a minimal set of metrics that will look for some basic success criteria.

### Success Criteria

The following metrics are logged on mlflow:

#### Metrics

- [ ]  % of filings captured in the SEC database
- [ ] % of docs with Ex. 21 that we can create a non-blank Ex. 21 PDF for
- [x] % of filers captured extracted by the "basic info extractor"
- [x] % of docs with Ex. 21 that are captured in the output ownership table
- [x] Filings it was unable to capture any data for

**Comment by katie-lamb** [comment]
@zschira does #34 make this issue obsolete?
