### ISSUE TITLE
Think about design for MVP PUDL integration infrastructure

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/mozilla-sec-eia#63]
Before going full steam ahead on implementation, it makes sense to think through the design a bit to see if there are any avoidable pitfalls.

Doc is [here](https://docs.google.com/document/d/1ot3eFBwsh-S2FiHM9Jc1NvMIiX7Ma6s607nhHAbRHFI/edit#heading=h.u9x2umyn474d).

### Success criteria
* [x] @katie-lamb sees no obvious issues with the design
* [x] one infrastructure person sees no obvious issues with the design

**Comment by jdangerx** [comment]
@zschira I took a look! directionally this looks good but I think there are still some big questions - and I think @katie-lamb had a few unanswered questions still also.

**Comment by zschira** [comment]
Closing, design doc reflects current design goals.
